export const managerEscalationThreshold = 100;

export const peopleSeed = [
  { name: "Aisling Murphy", email: "aisling@maplecourt.ie", role: "tenant" },
  { name: "Conor Walsh", email: "conor@harborhouse.ie", role: "tenant" },
  { name: "Niamh Byrne", email: "niamh@lindenmews.ie", role: "tenant" },
  { name: "Tom Doyle", email: "tom@rivergate.ie", role: "tenant" },
  { name: "Rory Keane", email: "rory@bricklane.ie", role: "tenant" },
  { name: "Maeve Flynn", email: "maeve@oakview.ie", role: "tenant" },
  { name: "Patrick O'Connell", email: "patrick.owner@harborhouse.ie", role: "landlord" },
  { name: "Eimear Scully", email: "eimear.owner@maplecourt.ie", role: "landlord" },
  { name: "John Brady", email: "john@bradyplumbing.ie", role: "contractor" },
  { name: "Sinead Kelleher", email: "sinead@spark-electric.ie", role: "contractor" },
  { name: "Leo Byrne", email: "leo@fixit-appliances.ie", role: "contractor" },
  { name: "Grace Nolan", email: "grace.prospect@gmail.com", role: "prospect" },
  { name: "Adam Shah", email: "adam.shah@email.com", role: "prospect" },
] as const;

export const propertySeed = [
  {
    code: "MAPLE",
    name: "Maple Court",
    addressLine1: "12 Maple Court",
    city: "Dublin 6",
  },
  {
    code: "HARBOR",
    name: "Harbor House",
    addressLine1: "8 Sir John Quay",
    city: "Dublin 1",
  },
  {
    code: "LINDEN",
    name: "Linden Mews",
    addressLine1: "4 Linden Street",
    city: "Dublin 8",
  },
  {
    code: "RIVER",
    name: "Rivergate Apartments",
    addressLine1: "19 Rivergate Lane",
    city: "Dublin 4",
  },
] as const;

export const unitSeed = [
  { propertyCode: "MAPLE", code: "MAPLE-2B", label: "2B", bedrooms: 2, listingStatus: "occupied" },
  { propertyCode: "HARBOR", code: "HARBOR-4C", label: "4C", bedrooms: 1, listingStatus: "occupied" },
  { propertyCode: "LINDEN", code: "LINDEN-1A", label: "1A", bedrooms: 2, listingStatus: "listed" },
  { propertyCode: "RIVER", code: "RIVER-5D", label: "5D", bedrooms: 3, listingStatus: "listed" },
  { propertyCode: "RIVER", code: "RIVER-2A", label: "2A", bedrooms: 1, listingStatus: "occupied" },
] as const;

export const tenancySeed = [
  {
    tenantEmail: "aisling@maplecourt.ie",
    propertyCode: "MAPLE",
    unitCode: "MAPLE-2B",
    status: "active",
    startedAt: "2025-07-01",
  },
  {
    tenantEmail: "conor@harborhouse.ie",
    propertyCode: "HARBOR",
    unitCode: "HARBOR-4C",
    status: "active",
    startedAt: "2024-10-01",
  },
  {
    tenantEmail: "niamh@lindenmews.ie",
    propertyCode: "LINDEN",
    unitCode: "LINDEN-1A",
    status: "notice_pending",
    startedAt: "2025-01-01",
  },
  {
    tenantEmail: "tom@rivergate.ie",
    propertyCode: "RIVER",
    unitCode: "RIVER-2A",
    status: "active",
    startedAt: "2025-03-01",
  },
] as const;

export const contractorSeed = [
  {
    name: "Brady Plumbing",
    email: "john@bradyplumbing.ie",
    trade: "plumber",
    serviceArea: "Dublin City",
    notes: "Emergency callout available weekday mornings.",
  },
  {
    name: "Spark Electric",
    email: "sinead@spark-electric.ie",
    trade: "electrician",
    serviceArea: "Dublin South",
    notes: "Best for fuse board and power fault issues.",
  },
  {
    name: "FixIt Appliances",
    email: "leo@fixit-appliances.ie",
    trade: "appliance",
    serviceArea: "Dublin",
    notes: "Covers washing machines, ovens, dishwashers and fridges.",
  },
] as const;

export const calendarSlotSeed = [
  {
    slotKey: "plumber-2026-03-09-0900",
    kind: "contractor",
    contractorEmail: "john@bradyplumbing.ie",
    propertyCode: "MAPLE",
    unitCode: "MAPLE-2B",
    startsAt: "2026-03-09T09:00:00.000Z",
    endsAt: "2026-03-09T10:00:00.000Z",
    label: "Mon Mar 9, 09:00 with Brady Plumbing",
  },
  {
    slotKey: "plumber-2026-03-10-1100",
    kind: "contractor",
    contractorEmail: "john@bradyplumbing.ie",
    propertyCode: "MAPLE",
    unitCode: "MAPLE-2B",
    startsAt: "2026-03-10T11:00:00.000Z",
    endsAt: "2026-03-10T12:00:00.000Z",
    label: "Tue Mar 10, 11:00 with Brady Plumbing",
  },
  {
    slotKey: "electrician-2026-03-09-1300",
    kind: "contractor",
    contractorEmail: "sinead@spark-electric.ie",
    propertyCode: "HARBOR",
    unitCode: "HARBOR-4C",
    startsAt: "2026-03-09T13:00:00.000Z",
    endsAt: "2026-03-09T14:00:00.000Z",
    label: "Mon Mar 9, 13:00 with Spark Electric",
  },
  {
    slotKey: "appliance-2026-03-10-1500",
    kind: "contractor",
    contractorEmail: "leo@fixit-appliances.ie",
    propertyCode: "HARBOR",
    unitCode: "HARBOR-4C",
    startsAt: "2026-03-10T15:00:00.000Z",
    endsAt: "2026-03-10T16:00:00.000Z",
    label: "Tue Mar 10, 15:00 with FixIt Appliances",
  },
  {
    slotKey: "viewing-linden-2026-03-10-1730",
    kind: "viewing",
    propertyCode: "LINDEN",
    unitCode: "LINDEN-1A",
    startsAt: "2026-03-10T17:30:00.000Z",
    endsAt: "2026-03-10T18:00:00.000Z",
    label: "Tue Mar 10, 17:30 at Linden Mews 1A",
  },
  {
    slotKey: "viewing-linden-2026-03-11-1815",
    kind: "viewing",
    propertyCode: "LINDEN",
    unitCode: "LINDEN-1A",
    startsAt: "2026-03-11T18:15:00.000Z",
    endsAt: "2026-03-11T18:45:00.000Z",
    label: "Wed Mar 11, 18:15 at Linden Mews 1A",
  },
  {
    slotKey: "viewing-river-2026-03-12-1200",
    kind: "viewing",
    propertyCode: "RIVER",
    unitCode: "RIVER-5D",
    startsAt: "2026-03-12T12:00:00.000Z",
    endsAt: "2026-03-12T12:30:00.000Z",
    label: "Thu Mar 12, 12:00 at Rivergate 5D",
  },
  {
    slotKey: "viewing-river-2026-03-12-1830",
    kind: "viewing",
    propertyCode: "RIVER",
    unitCode: "RIVER-5D",
    startsAt: "2026-03-12T18:30:00.000Z",
    endsAt: "2026-03-12T19:00:00.000Z",
    label: "Thu Mar 12, 18:30 at Rivergate 5D",
  },
] as const;

export const jobCatalogSeed = [
  {
    code: "dripping_tap",
    title: "Dripping tap",
    trade: "plumber",
    typicalCostMin: 65,
    typicalCostMax: 95,
    keywords: ["dripping tap", "tap drip", "tap leaking"],
  },
  {
    code: "blocked_sink",
    title: "Blocked sink",
    trade: "plumber",
    typicalCostMin: 85,
    typicalCostMax: 120,
    keywords: ["blocked sink", "sink blocked", "won't drain", "not draining"],
  },
  {
    code: "toilet_issue",
    title: "Toilet issue",
    trade: "plumber",
    typicalCostMin: 90,
    typicalCostMax: 150,
    keywords: ["toilet", "flush", "cistern"],
  },
  {
    code: "leak_investigation",
    title: "Leak investigation",
    trade: "plumber",
    typicalCostMin: 120,
    typicalCostMax: 240,
    keywords: ["ceiling leaking", "water coming through", "leak from above", "major leak"],
  },
  {
    code: "washing_machine_fault",
    title: "Washing machine fault",
    trade: "appliance",
    typicalCostMin: 90,
    typicalCostMax: 180,
    keywords: ["washing machine", "mid cycle", "spin", "laundry"],
  },
  {
    code: "oven_fault",
    title: "Oven fault",
    trade: "appliance",
    typicalCostMin: 110,
    typicalCostMax: 220,
    keywords: ["oven", "hob", "cooker"],
  },
  {
    code: "fridge_fault",
    title: "Fridge fault",
    trade: "appliance",
    typicalCostMin: 140,
    typicalCostMax: 280,
    keywords: ["fridge", "freezer"],
  },
  {
    code: "dishwasher_fault",
    title: "Dishwasher fault",
    trade: "appliance",
    typicalCostMin: 95,
    typicalCostMax: 180,
    keywords: ["dishwasher"],
  },
  {
    code: "broken_socket",
    title: "Broken socket",
    trade: "electrician",
    typicalCostMin: 70,
    typicalCostMax: 110,
    keywords: ["socket", "plug", "outlet"],
  },
  {
    code: "light_failure",
    title: "Lighting issue",
    trade: "electrician",
    typicalCostMin: 60,
    typicalCostMax: 95,
    keywords: ["light", "lighting", "bulb"],
  },
  {
    code: "fuse_issue",
    title: "Fuse or breaker issue",
    trade: "electrician",
    typicalCostMin: 110,
    typicalCostMax: 190,
    keywords: ["fuse", "breaker", "power tripped", "tripped power"],
  },
  {
    code: "lock_issue",
    title: "Lock issue",
    trade: "handyman",
    typicalCostMin: 85,
    typicalCostMax: 130,
    keywords: ["lock", "front door", "key sticking"],
  },
  {
    code: "door_issue",
    title: "Door issue",
    trade: "handyman",
    typicalCostMin: 70,
    typicalCostMax: 125,
    keywords: ["door", "hinge", "close properly"],
  },
] as const;

export const emailSeed = [
  {
    scenarioKey: "spam-roofing-vendor",
    sourceLabel: "Cold sales outreach",
    fromName: "Elite Roofing Leads",
    fromEmail: "growth@eliteroofingleads.com",
    subject: "Triple your maintenance margins this quarter",
    sentAt: "2026-03-07T08:04:00.000Z",
    body:
      "Hi team, we can guarantee 40 exclusive roofing leads a week if you sign up today. Not about a property issue, just a quick sales opportunity.",
  },
  {
    scenarioKey: "irrelevant-newsletter",
    sourceLabel: "Irrelevant newsletter",
    fromName: "City Food Digest",
    fromEmail: "editor@cityfooddigest.ie",
    subject: "This week's lunch offers near Grand Canal Dock",
    sentAt: "2026-03-07T08:14:00.000Z",
    body:
      "You subscribed at some point to our Dublin lunch round-up. Here are the five best sandwiches this week.",
  },
  {
    scenarioKey: "rent-details",
    sourceLabel: "Routine tenant request",
    fromName: "Aisling Murphy",
    fromEmail: "aisling@maplecourt.ie",
    subject: "Where should I send this month's rent?",
    sentAt: "2026-03-07T08:28:00.000Z",
    body:
      "Morning, I changed banks and want to make sure I am sending the March payment to the correct IBAN for Maple Court 2B.",
  },
  {
    scenarioKey: "portal-question",
    sourceLabel: "Routine tenant request",
    fromName: "Tom Doyle",
    fromEmail: "tom@rivergate.ie",
    subject: "Can you resend the maintenance portal link?",
    sentAt: "2026-03-07T08:34:00.000Z",
    body:
      "I cannot find the last email with the portal login. This is for Rivergate 2A. Could you send the right link again?",
  },
  {
    scenarioKey: "dripping-tap",
    sourceLabel: "Low-cost maintenance",
    fromName: "Aisling Murphy",
    fromEmail: "aisling@maplecourt.ie",
    subject: "Kitchen tap dripping in 2B",
    sentAt: "2026-03-07T08:42:00.000Z",
    body:
      "Hi, the kitchen tap in Maple Court 2B has been dripping constantly since last night. It is annoying but not urgent. I am home Monday morning if a plumber needs access.",
  },
  {
    scenarioKey: "blocked-sink",
    sourceLabel: "Maintenance over threshold",
    fromName: "Aisling Murphy",
    fromEmail: "aisling@maplecourt.ie",
    subject: "Bathroom sink not draining and smell getting worse",
    sentAt: "2026-03-07T08:51:00.000Z",
    body:
      "The bathroom sink in 2B is blocked and now there is a bad smell from the pipe underneath. Water sits there for ages. Can someone take a look?",
  },
  {
    scenarioKey: "washing-machine-fault",
    sourceLabel: "Appliance issue",
    fromName: "Conor Walsh",
    fromEmail: "conor@harborhouse.ie",
    subject: "Washing machine stopped mid cycle and tripped power",
    sentAt: "2026-03-07T09:05:00.000Z",
    body:
      "Hi, Harbor House 4C here. The washing machine stopped halfway through and after that the utility socket would not come back on. I have laundry sitting in it now.",
  },
  {
    scenarioKey: "ceiling-leak",
    sourceLabel: "Critical maintenance",
    fromName: "Conor Walsh",
    fromEmail: "conor@harborhouse.ie",
    subject: "Water coming through bathroom ceiling",
    sentAt: "2026-03-07T09:14:00.000Z",
    body:
      "Urgent. Water is coming through the bathroom ceiling in Harbor House 4C and dripping onto the floor. I have put down towels but it is getting worse.",
  },
  {
    scenarioKey: "tenancy-notice",
    sourceLabel: "Tenancy termination",
    fromName: "Niamh Byrne",
    fromEmail: "niamh@lindenmews.ie",
    subject: "Notice to terminate tenancy at Linden Mews 1A",
    sentAt: "2026-03-07T09:23:00.000Z",
    body:
      "Please treat this as my formal notice to end the tenancy for Linden Mews 1A. I expect to move out by 30 April 2026 and wanted to understand the inspection and deposit steps.",
  },
  {
    scenarioKey: "viewing-request-linden",
    sourceLabel: "Prospect viewing",
    fromName: "Grace Nolan",
    fromEmail: "grace.prospect@gmail.com",
    subject: "Can I view Linden Mews 1A next week?",
    sentAt: "2026-03-07T09:31:00.000Z",
    body:
      "Hi, I saw the listing for Linden Mews 1A. I work until 5 and could do Tuesday or Wednesday evening. Are pets considered?",
  },
  {
    scenarioKey: "viewing-request-river",
    sourceLabel: "Prospect viewing",
    fromName: "Adam Shah",
    fromEmail: "adam.shah@email.com",
    subject: "Viewing request for Rivergate 5D",
    sentAt: "2026-03-07T09:36:00.000Z",
    body:
      "I am interested in Rivergate 5D and would love a quick viewing after work. Thursday evening would be ideal if available.",
  },
  {
    scenarioKey: "landlord-update",
    sourceLabel: "Landlord request",
    fromName: "Patrick O'Connell",
    fromEmail: "patrick.owner@harborhouse.ie",
    subject: "Need an update on the Harbor House appliance issue",
    sentAt: "2026-03-07T09:44:00.000Z",
    body:
      "Can you tell me what is going on in Harbor House 4C and whether we are likely to need a replacement appliance? I want visibility before approving anything expensive.",
  },
  {
    scenarioKey: "contractor-reschedule",
    sourceLabel: "Contractor coordination",
    fromName: "John Brady",
    fromEmail: "john@bradyplumbing.ie",
    subject: "Can do Tuesday 11 instead of Monday 9",
    sentAt: "2026-03-07T09:53:00.000Z",
    body:
      "For Maple Court 2B I can do Tuesday at 11:00 instead of Monday at 09:00 if the tenant can make that. Monday has just filled up.",
  },
  {
    scenarioKey: "arrival-window",
    sourceLabel: "Routine tenant follow-up",
    fromName: "Aisling Murphy",
    fromEmail: "aisling@maplecourt.ie",
    subject: "What time would the plumber arrive roughly?",
    sentAt: "2026-03-07T10:05:00.000Z",
    body:
      "Just checking whether the plumber slot for Maple Court 2B would be morning or more around lunch, so I can plan work calls.",
  },
  {
    scenarioKey: "heating-complaint",
    sourceLabel: "Tenant complaint",
    fromName: "Maeve Flynn",
    fromEmail: "maeve@oakview.ie",
    subject: "Heating still cutting out after last fix",
    sentAt: "2026-03-07T10:16:00.000Z",
    body:
      "Someone looked at the heating last week but it keeps cutting out in the evening. I am not sure whether this is the same issue coming back or something worse.",
  },
  {
    scenarioKey: "out-of-portfolio",
    sourceLabel: "Out of portfolio",
    fromName: "Colm Brennan",
    fromEmail: "colm.brennan@email.com",
    subject: "Do you manage 14 Cedar Park?",
    sentAt: "2026-03-07T10:22:00.000Z",
    body:
      "I was given this email address to ask about 14 Cedar Park. I cannot tell if you are the right people for that property.",
  },
  {
    scenarioKey: "lease-change",
    sourceLabel: "Tenancy admin",
    fromName: "Rory Keane",
    fromEmail: "rory@bricklane.ie",
    subject: "Can my partner be added to the lease?",
    sentAt: "2026-03-07T10:31:00.000Z",
    body:
      "Hi, could you tell me the process to add my partner to the tenancy agreement? I am not sure what checks or paperwork you need.",
  },
  {
    scenarioKey: "access-code",
    sourceLabel: "Contractor request",
    fromName: "Sinead Kelleher",
    fromEmail: "sinead@spark-electric.ie",
    subject: "Need access details for Harbor House 4C visit",
    sentAt: "2026-03-07T10:39:00.000Z",
    body:
      "Before I head to Harbor House 4C I need to know whether there is a gate code or concierge handoff for access.",
  },
  {
    scenarioKey: "lock-issue",
    sourceLabel: "Security-related maintenance",
    fromName: "Tom Doyle",
    fromEmail: "tom@rivergate.ie",
    subject: "Front door lock sticking badly",
    sentAt: "2026-03-07T10:46:00.000Z",
    body:
      "The front door lock in Rivergate 2A is sticking and this morning I had to try the key several times before it opened. I am worried it may fail completely.",
  },
  {
    scenarioKey: "oven-issue",
    sourceLabel: "Appliance maintenance",
    fromName: "Conor Walsh",
    fromEmail: "conor@harborhouse.ie",
    subject: "Oven not heating properly now either",
    sentAt: "2026-03-07T10:54:00.000Z",
    body:
      "Adding this because the oven in 4C is also not heating evenly and one side stays cold. Not an emergency but it is making the flat awkward to use.",
  },
] as const;
